### ISSUE TITLE
config.txt does it support all rasperberry pi paramters?

### ISSUE THREAD

**Issue by dstewen** [siderolabs/sbc-raspberrypi#32]
Referring to https://github.com/siderolabs/sbc-raspberrypi/blob/main/installers/rpi_generic/src/config.txt  

I would like to use the following in config.txt

```
      over_voltage=6
      arm_freq=2000
```

```
overlay:
  name: rpi_generic
  image: siderolabs/sbc-raspberrypi
  options:
    configTxt: |
      gpu_mem=32
      hdmi_force_hotplug:0=1
      hdmi_force_hotplug:1=1
      kernel=u-boot.bin
      arm_64bit=1
      arm_boost=1
      enable_uart=1
      dtoverlay=disable-bt
      dtoverlay=disable-wifi
      over_voltage=6
      arm_freq=2000
customization:
  systemExtensions:
    officialExtensions: []
```

I know the parameters work on the models under Raspberry's OS and under Debian but wanted to check if they should work with Talos?

**Comment by frezbo** [comment]
`configTxt` is used as is, talos doesn;t do any validations on it, so whatever the user provided is passed as is
